name: CI

# Trigger CI for pull requests to the main branch or when a release is made
# Do not trigger CI for draft pull request
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:  
    types: [opened, synchronize, reopened, ready_for_review]


jobs:
  build:
    name: Package building || Pythom ${{ matrix.python-version }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version:
          - "3.10"
        os:
          - ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
  doc:
    name: Doc deployment || Pythom ${{ matrix.python-version }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version:
          - "3.10"
        os:
          - ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Build the package
        run: python -m pip install .

      - name: Install the documentation dependencies
        run: python -m pip install .[docs]

      - name: Build the documentation
        run: sphinx-multiversion docs docs/build/html

      - name: Deploy the documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
